# Generated by Django 5.0 on 2024-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=600)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.ImageField(upload_to='Uploaded_photos', verbose_name='Photos')),
                ('views', models.IntegerField(blank=True, default=0)),
                ('likes', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
